In [339]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn import tree
from sklearn.model_selection import GridSearchCV
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
# from pyspark import *
# from pyspark.mllib.feature import *
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import *
from sklearn import *
from sklearn.metrics import *
# from pyspark.sql import *
# import pyspark.sql.functions as F
# import pyspark.sql.types as T
# from pyspark.ml.classification import *
from pandas import *
# from datetime import date
from sklearn.feature_extraction.text import *
from sklearn.feature_extraction.text import *
from sklearn.feature_extraction.text import *
from sklearn.naive_bayes import *
from sklearn.metrics import *
from gensim import *
from gensim.models import *
# from pyspark.mllib.feature import *


In [340]:
docs=["the house had a tiny little mouse",
      "the cat saw the mouse",
      "the mouse ran away from the house",
      "the cat finally ate the mouse",
      "the end of the mouse story"
     ]

In [341]:
# Bow
vect = CountVectorizer()
x = vect.fit_transform(docs)
x.toarray()

array([[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 2, 0],
       [0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 2, 0],
       [1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 2, 0]])

In [342]:
# tf-idf
vect2 = TfidfVectorizer(stop_words='english')
x_tfidf = vect2.fit_transform(docs)
x_tfidf.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.4755751 , 0.58946308, 0.28088232, 0.        , 0.        ,
        0.        , 0.58946308],
       [0.        , 0.        , 0.58873218, 0.        , 0.        ,
        0.        , 0.        , 0.34771471, 0.        , 0.72971837,
        0.        , 0.        ],
       [0.        , 0.58946308, 0.        , 0.        , 0.        ,
        0.4755751 , 0.        , 0.28088232, 0.58946308, 0.        ,
        0.        , 0.        ],
       [0.58946308, 0.        , 0.4755751 , 0.        , 0.58946308,
        0.        , 0.        , 0.28088232, 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.67009179, 0.        ,
        0.        , 0.        , 0.31930233, 0.        , 0.        ,
        0.67009179, 0.        ]])

In [343]:
def featureVecMethod(words, model, num_features):
    featureVec = np.zeros(num_features,dtype="float32")
    nwords = 0
    
    index2word_set = set(model.wv.index2word)
    
    for word in  words:
        if word in index2word_set:
            nwords = nwords + 1
            featureVec = np.add(featureVec,model[word])
    
    featureVec = np.divide(featureVec, nwords)
    return featureVec

In [344]:
def getAvgFeatureVecs(reviews, model, num_features):
    counter = 0
    reviewFeatureVecs = np.zeros((len(reviews),num_features),dtype="float32")
    for review in reviews:            
        reviewFeatureVecs[counter] = featureVecMethod(review, model, num_features)
        counter = counter+1
        
    return reviewFeatureVecs

In [345]:
traindata = []
#     sents = open(pathdata, 'r').readlines()
for sent in docs:
    traindata.append(sent.split())
    
model = Word2Vec(traindata, size=150, window=10, min_count=2, workers=4, sg=0)
model.wv.save("word2vec.model")

In [346]:
trainDataVecs = getAvgFeatureVecs( traindata, model, 150 )

<ipython-input-343-0040bdedc0c8>:10: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  featureVec = np.add(featureVec,model[word])


In [347]:
trainDataVecs

array([[-2.53158680e-04,  7.50321429e-04,  8.49443313e-04,
         3.42864842e-05, -1.73477444e-03,  1.61706901e-03,
        -4.84731019e-04,  1.26640371e-03, -1.03002903e-03,
        -3.15587822e-04, -2.89037474e-04, -4.30013140e-04,
         1.56973850e-03, -6.63011102e-04,  8.21711030e-04,
        -8.43898568e-04,  2.06229254e-03, -5.12252627e-05,
         5.97625331e-04, -9.42162529e-04,  2.20726055e-04,
         1.17410335e-03, -1.22976862e-03,  1.46143034e-03,
        -1.52219320e-04,  3.03723122e-04,  9.18616483e-04,
        -1.07662182e-03,  2.46208045e-03,  1.14525587e-03,
         1.97980576e-03, -9.18206933e-04,  8.26878881e-04,
        -1.57506473e-03, -2.52455618e-04,  1.15964947e-04,
        -3.25271860e-04,  1.31647103e-05, -2.65433802e-04,
        -5.74794598e-04, -8.34939827e-04, -5.06345939e-04,
         4.42162243e-04, -5.87748364e-04, -3.70523514e-04,
        -2.06565578e-03,  1.09439215e-03,  1.26041193e-03,
        -9.92147368e-04, -4.73496038e-05,  6.47335663e-0